version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: npm run dev
    environment:
      DB_HOST: db
      DB_NAME: auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      ACCESS_TOKEN_SECRET: youraccesstokensecret
      REFRESH_TOKEN_SECRET: yourrefreshtokensecret
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata: